[project]
name = "lwa-agent"
version = "0.1.0"
description = "LangGraph Agent with RAG"
requires-python = ">=3.10"

dependencies = [
    "flask",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-groq",
    "python-dotenv",
    "flask-smorest",
    "flask-marshmallow",
    "sqlalchemy",
    "flask-sqlalchemy",
    "sqlalchemy-utils",
    "langgraph",
    "ipykernel",
    "langgraph-cli[inmem]>=0.4.31",
    "wikipedia>=1.4.0",
    "boto3>=1.43.89",
    "bedrock-agentcore>=1.22.0",
    "bedrock-agentcore-starter-toolkit>=0.3.12",
    "langchain-aws>=1.7.5",
    "langchain-tavily>=0.2.18",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
