[project]
name = "lwa-agent"
version = "0.1.0"
description = "LangGraph Agent with RAG"
requires-python = ">=3.9"

dependencies = [
    "flask",
    "langchain[aws]",
    "langchain-community",
    "langchain-openai",
    "langchain-groq",
    "python-dotenv",
    "flask-smorest",
    "flask-marshmallow",
    "sqlalchemy",
    "flask-sqlalchemy",
    "sqlalchemy-utils",
    "langgraph",
    "ipykernel",
    "langgraph-cli[inmem]>=0.4.3",
    "wikipedia>=1.4.0",
    "boto3>=1.42.97",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
